const emojiContainer = document.getElementById("emojiContainer");
const searchInput = document.getElementById("searchInput");

// Function to filter emojis based on search input
function filterEmojis() {
  const searchQuery = searchInput.value.toLowerCase();
  const filteredEmojis = emojis.filter((emoji) => {
    return emoji.keywords.some((keyword) => keyword.includes(searchQuery));
  });

  displayEmojis(filteredEmojis);
}

// Function to display emojis in the emoji container
function displayEmojis(emojis) {
  emojiContainer.innerHTML = "";

  emojis.forEach((emoji) => {
    const emojiElement = document.createElement("span");
    emojiElement.textContent = emoji.symbol;
    emojiElement.classList.add("emoji");

    // Copy emoji to clipboard on click
    emojiElement.addEventListener("click", () => {
      navigator.clipboard.writeText(emoji.symbol);
      alert("Copied to clipboard!");
    });

    emojiContainer.appendChild(emojiElement);
  });
}

const emojis = [
  { symbol: "😀", keywords: ["grinning", "happy", "smile"] },
  { symbol: "😂", keywords: ["laugh", "tears", "funny"] },
  { symbol: "🥰", keywords: ["love", "hearts", "affection"] },
  { symbol: "😎", keywords: ["cool", "sunglasses", "attitude"] },
  { symbol: "😢", keywords: ["sad", "tear", "cry"] },
  { symbol: "😡", keywords: ["angry", "mad", "frustrated"] },
  { symbol: "👍", keywords: ["thumbs up", "approve", "like"] },
  { symbol: "👎", keywords: ["thumbs down", "disapprove", "dislike"] },
  { symbol: "👏", keywords: ["clap", "applause", "praise"] },
  { symbol: "🙏", keywords: ["pray", "please", "thank you"] },
  { symbol: "🐶", keywords: ["dog", "puppy", "pet"] },
  { symbol: "🐱", keywords: ["cat", "kitty", "pet"] },
  { symbol: "🦊", keywords: ["fox", "animal", "wild"] },
  { symbol: "👑", keywords: ["king", "queen", "royalty"] },
  { symbol: "🧩", keywords: ["puzzle", "game", "piece"] },
  { symbol: "🌌", keywords: ["galaxy", "stars", "space"] },
  { symbol: "🌍", keywords: ["earth", "world", "planet"] },
  { symbol: "🛸", keywords: ["UFO", "alien", "spacecraft"] },
  { symbol: "💡", keywords: ["idea", "light", "innovation"] },
  { symbol: "⛷️", keywords: ["skier", "snow", "sports"] },
  { symbol: "🎭", keywords: ["theater", "mask", "drama"] },
  { symbol: "🏖️", keywords: ["vacation", "beach", "holiday"] },
  { symbol: "🎢", keywords: ["roller coaster", "amusement park", "fun"] },
  { symbol: "🧳", keywords: ["luggage", "travel", "bag"] },
  { symbol: "🍿", keywords: ["popcorn", "movie", "snack"] },
  { symbol: "💌", keywords: ["love letter", "message", "romantic"] },
  { symbol: "🏰", keywords: ["castle", "fortress", "architecture"] },
  { symbol: "🏙️", keywords: ["city", "urban", "skyscrapers"] },
  { symbol: "⛷️", keywords: ["snow", "ski", "winter sport"] },
  { symbol: "🌱", keywords: ["plant", "growth", "nature"] },
  { symbol: "🚀", keywords: ["space", "rocket", "exploration"] },
  { symbol: "🖋️", keywords: ["pen", "writing", "author"] },
  { symbol: "🔮", keywords: ["crystal ball", "magic", "mystical"] },
  { symbol: "🧚", keywords: ["fairy", "magic", "fantasy"] },
  { symbol: "👽", keywords: ["alien", "extraterrestrial", "UFO"] },
  { symbol: "🍇", keywords: ["grapes", "fruit", "vine"] },
  { symbol: "🍷", keywords: ["wine", "drink", "alcohol"] },
  { symbol: "🧘", keywords: ["meditation", "yoga", "calm"] },
  { symbol: "💎", keywords: ["diamond", "luxury", "gemstone"] },
  { symbol: "🛀", keywords: ["bath", "relax", "spa"] },
  { symbol: "🎶", keywords: ["music", "notes", "melody"] },
  { symbol: "🧑‍🔬", keywords: ["scientist", "lab", "research"] },
  { symbol: "🚲", keywords: ["bicycle", "bike", "transport"] },
  { symbol: "🏄‍♀️", keywords: ["surfing", "beach", "sport"] },
  { symbol: "🦓", keywords: ["zebra", "animal", "wildlife"] },
  { symbol: "🐉", keywords: ["dragon", "mythical", "creature"] },
  { symbol: "🦗", keywords: ["cricket", "insect", "nature"] },
  { symbol: "🍪", keywords: ["cookie", "dessert", "sweet"] },
  { symbol: "🍔", keywords: ["burger", "fast food", "meal"] },
  { symbol: "🦐", keywords: ["shrimp", "seafood", "ocean"] },
  { symbol: "🧀", keywords: ["cheese", "dairy", "food"] },
  { symbol: "🎣", keywords: ["fishing", "sport", "outdoor"] },
  { symbol: "⛺", keywords: ["tent", "camping", "outdoor"] },
  { symbol: "🌍", keywords: ["earth", "world", "global"] },
  { symbol: "🛶", keywords: ["canoe", "boat", "water"] },
  { symbol: "🚠", keywords: ["cable car", "mountain", "transport"] },
  { symbol: "💸", keywords: ["money", "cash", "wealth"] },
  { symbol: "🎤", keywords: ["microphone", "singing", "music"] },
  { symbol: "🍒", keywords: ["cherry", "fruit", "red"] },
  { symbol: "🏞️", keywords: ["nature", "mountain", "landscape"] },
  { symbol: "🏰", keywords: ["castle", "historical", "architecture"] },
  { symbol: "🏝️", keywords: ["island", "vacation", "tropical"] },
  { symbol: "⛰️", keywords: ["mountain", "outdoor", "landscape"] },
  { symbol: "🏙️", keywords: ["city", "skyline", "urban"] },
  { symbol: "🏒", keywords: ["hockey", "sport", "ice"] },
  { symbol: "🛳️", keywords: ["ship", "ocean", "travel"] },
  { symbol: "🎢", keywords: ["roller coaster", "amusement", "fun"] },
  { symbol: "🐧", keywords: ["penguin", "animal", "cold"] },
  { symbol: "🦀", keywords: ["crab", "seafood", "ocean"] },
  { symbol: "🏀", keywords: ["basketball", "sport", "game"] },
  { symbol: "🎮", keywords: ["gaming", "controller", "video game"] },
  { symbol: "🚴", keywords: ["cycling", "exercise", "sport"] },
  { symbol: "🏄", keywords: ["surfing", "ocean", "sport"] },
  { symbol: "🍩", keywords: ["donut", "dessert", "sweet"] },
  { symbol: "🌶️", keywords: ["spicy", "food", "pepper"] },
  { symbol: "🍉", keywords: ["watermelon", "fruit", "summer"] },
  { symbol: "🏕️", keywords: ["camping", "outdoor", "nature"] },
  { symbol: "🐢", keywords: ["turtle", "slow", "animal"] },
  { symbol: "🦘", keywords: ["kangaroo", "animal", "wildlife"] },
  { symbol: "🦛", keywords: ["hippopotamus", "animal", "wild"] },
  { symbol: "🍆", keywords: ["eggplant", "vegetable", "food"] },
  { symbol: "🧇", keywords: ["waffle", "breakfast", "dessert"] },
  { symbol: "🦉", keywords: ["owl", "bird", "wise"] },
  { symbol: "🌪️", keywords: ["tornado", "storm", "weather"] },
  { symbol: "🍍", keywords: ["pineapple", "fruit", "tropical"] },
  { symbol: "🍪", keywords: ["cookie", "dessert", "snack"] },
  { symbol: "🎯", keywords: ["target", "aim", "shooting"] },
  { symbol: "😀", keywords: ["grinning", "happy", "joyful"] },
  { symbol: "😁", keywords: ["beaming", "grin", "smile"] },
  { symbol: "😆", keywords: ["laughing", "joy", "silly"] },
  { symbol: "😄", keywords: ["smiling", "teeth", "happy"] },
  { symbol: "😃", keywords: ["grinning", "wide smile", "joy"] },
  { symbol: "😊", keywords: ["smiling", "shy", "blush"] },
  { symbol: "☺️", keywords: ["content", "blissful", "soft smile"] },
  { symbol: "😎", keywords: ["cool", "sunglasses", "confident"] },
  { symbol: "😋", keywords: ["delicious", "yummy", "tongue out"] },
  { symbol: "😜", keywords: ["wink", "playful", "tongue out"] },
  { symbol: "😝", keywords: ["face with tongue", "playful", "funny"] },
  { symbol: "😛", keywords: ["tongue out", "cheeky", "silly"] },
  { symbol: "😏", keywords: ["smirk", "playful", "flirt"] },
  { symbol: "😒", keywords: ["unamused", "disappointed", "irritated"] },
  { symbol: "😔", keywords: ["sad", "disappointed", "down"] },
  { symbol: "😞", keywords: ["disappointed", "sad", "unhappy"] },
  { symbol: "😢", keywords: ["crying", "sad", "tears"] },
  { symbol: "😭", keywords: ["sobbing", "crying", "emotional"] },
  { symbol: "😤", keywords: ["angry", "frustrated", "steam out"] },
  { symbol: "😡", keywords: ["angry", "mad", "fuming"] },
  { symbol: "🤬", keywords: ["rage", "swearing", "angry"] },
  { symbol: "😱", keywords: ["scream", "fear", "scared"] },
  { symbol: "😨", keywords: ["fear", "scared", "worried"] },
  { symbol: "😰", keywords: ["nervous", "anxious", "sweating"] },
  { symbol: "😳", keywords: ["embarrassed", "shocked", "flustered"] },
  { symbol: "😵", keywords: ["dizzy", "confused", "stunned"] },
  { symbol: "😵‍💫", keywords: ["dizzy", "spinning", "confused"] },
  { symbol: "🤯", keywords: ["mind blown", "shocked", "overwhelmed"] },
  { symbol: "😮", keywords: ["surprised", "shock", "amazement"] },
  { symbol: "😲", keywords: ["amazed", "surprised", "astonished"] },
  { symbol: "🥺", keywords: ["pleading", "puppy eyes", "adorable"] },
  { symbol: "😌", keywords: ["calm", "relaxed", "content"] },
  { symbol: "😔", keywords: ["sad", "down", "unhappy"] },
  { symbol: "😷", keywords: ["sick", "ill", "mask"] },
  { symbol: "🤒", keywords: ["sick", "fever", "ill"] },
  { symbol: "🤕", keywords: ["injured", "hurt", "bandage"] },
  { symbol: "🥴", keywords: ["dizzy", "drunk", "confused"] },
  { symbol: "🤑", keywords: ["money", "rich", "money mouth"] },
  { symbol: "🤠", keywords: ["cowboy", "hat", "western"] },
  { symbol: "👩‍🦳", keywords: ["woman", "grey hair", "elderly"] },
  { symbol: "👨‍🦳", keywords: ["man", "grey hair", "elderly"] },
  { symbol: "👩‍🦰", keywords: ["woman", "red hair", "ginger"] },
  { symbol: "👨‍🦰", keywords: ["man", "red hair", "ginger"] },
  { symbol: "👩‍🦱", keywords: ["woman", "curly hair", "afro"] },
  { symbol: "👨‍🦱", keywords: ["man", "curly hair", "afro"] },
  { symbol: "👩‍🦲", keywords: ["woman", "bald", "shaved"] },
  { symbol: "👨‍🦲", keywords: ["man", "bald", "shaved"] },
  { symbol: "🤳", keywords: ["selfie", "phone", "portrait"] },
  { symbol: "👯‍♂️", keywords: ["two men", "dancing", "partners"] },
  { symbol: "👯‍♀️", keywords: ["two women", "dancing", "partners"] },
  { symbol: "👫", keywords: ["couple", "man and woman", "together"] },
  { symbol: "👬", keywords: ["couple", "two men", "love"] },
  { symbol: "👭", keywords: ["couple", "two women", "love"] },
  { symbol: "🧑‍🤝‍🧑", keywords: ["people holding hands", "unity", "together"] },
  { symbol: "🧑‍🦯", keywords: ["person with cane", "blind", "accessibility"] },
  {
    symbol: "🧑‍🦽",
    keywords: ["person in wheelchair", "disability", "accessibility"],
  },
  { symbol: "👨‍🦳", keywords: ["elderly", "man", "grey hair"] },
  { symbol: "👩‍🦳", keywords: ["elderly", "woman", "grey hair"] },
  { symbol: "🧑‍🦳", keywords: ["elderly", "person", "grey hair"] },
  { symbol: "🧑‍🦰", keywords: ["ginger", "person", "red hair"] },
  { symbol: "🧑‍🦱", keywords: ["curly hair", "person", "afro"] },
  { symbol: "🧑‍🦲", keywords: ["shaved head", "person", "bald"] },
  { symbol: "🧣", keywords: ["scarf", "winter", "clothing"] },
  { symbol: "🧊", keywords: ["ice", "cold", "freeze"] },
  { symbol: "🎲", keywords: ["dice", "game", "luck"] },
  { symbol: "🎤", keywords: ["singing", "mic", "music"] },
  { symbol: "🐻", keywords: ["bear", "animal", "cute"] },
  { symbol: "🐼", keywords: ["panda", "cute", "animal"] },
  { symbol: "🦁", keywords: ["lion", "king", "wild"] },
  { symbol: "🐯", keywords: ["tiger", "wild", "animal"] },
  { symbol: "🐸", keywords: ["frog", "green", "amphibian"] },
  { symbol: "🐧", keywords: ["penguin", "cold", "animal"] },
  { symbol: "🐔", keywords: ["chicken", "hen", "farm"] },
  { symbol: "🐤", keywords: ["chick", "baby", "bird"] },
  { symbol: "🐣", keywords: ["hatch", "egg", "spring"] },
  { symbol: "🦆", keywords: ["duck", "pond", "bird"] },
  { symbol: "🐢", keywords: ["turtle", "slow", "animal"] },
  { symbol: "🐬", keywords: ["dolphin", "sea", "swim"] },
  { symbol: "🐳", keywords: ["whale", "ocean", "big"] },
  { symbol: "🐟", keywords: ["fish", "sea", "animal"] },
  { symbol: "🦋", keywords: ["butterfly", "insect", "fly"] },
  { symbol: "🌸", keywords: ["flower", "blossom", "spring"] },
  { symbol: "🌻", keywords: ["sunflower", "bright", "flower"] },
  { symbol: "🌼", keywords: ["daisy", "flower", "spring"] },
  { symbol: "🌹", keywords: ["rose", "love", "romance"] },
  { symbol: "🍕", keywords: ["pizza", "food", "cheese"] },
  { symbol: "🍔", keywords: ["burger", "fast food", "meat"] },
  { symbol: "🍟", keywords: ["fries", "snack", "crispy"] },
  { symbol: "🌮", keywords: ["taco", "mexican", "food"] },
  { symbol: "🍣", keywords: ["sushi", "japanese", "fish"] },
  { symbol: "🍩", keywords: ["donut", "sweet", "dessert"] },
  { symbol: "🍪", keywords: ["cookie", "biscuit", "chocolate"] },
  { symbol: "🍰", keywords: ["cake", "dessert", "birthday"] },
  { symbol: "🎂", keywords: ["birthday", "cake", "celebration"] },
  { symbol: "🍦", keywords: ["ice cream", "summer", "cold"] },
  { symbol: "🍫", keywords: ["chocolate", "candy", "sweet"] },
  { symbol: "🍎", keywords: ["apple", "fruit", "healthy"] },
  { symbol: "🍉", keywords: ["watermelon", "fruit", "summer"] },
  { symbol: "🍓", keywords: ["strawberry", "fruit", "red"] },
  { symbol: "🍌", keywords: ["banana", "fruit", "yellow"] },
  { symbol: "🍇", keywords: ["grapes", "fruit", "vine"] },
  { symbol: "🍍", keywords: ["pineapple", "fruit", "tropical"] },
  { symbol: "🥑", keywords: ["avocado", "fruit", "healthy"] },
  { symbol: "🥦", keywords: ["broccoli", "vegetable", "green"] },
  { symbol: "🥕", keywords: ["carrot", "vegetable", "orange"] },
  { symbol: "🌈", keywords: ["rainbow", "color", "sky"] },
  { symbol: "⚡", keywords: ["lightning", "electric", "energy"] },
  { symbol: "🔥", keywords: ["fire", "hot", "lit"] },
  { symbol: "💧", keywords: ["water", "drop", "wet"] },
  { symbol: "☀️", keywords: ["sun", "bright", "day"] },
  { symbol: "🌙", keywords: ["moon", "night", "sleep"] },
  { symbol: "☁️", keywords: ["cloud", "sky", "weather"] },
  { symbol: "🌪️", keywords: ["tornado", "storm", "wind"] },
  { symbol: "🌊", keywords: ["wave", "ocean", "sea"] },
  { symbol: "🎉", keywords: ["party", "celebration", "confetti"] },
  { symbol: "🎈", keywords: ["balloon", "birthday", "celebrate"] },
  { symbol: "🎁", keywords: ["gift", "present", "surprise"] },
  { symbol: "🎵", keywords: ["music", "note", "melody"] },
  { symbol: "🎤", keywords: ["mic", "sing", "karaoke"] },
  { symbol: "🎧", keywords: ["headphones", "music", "listen"] },
  { symbol: "🎮", keywords: ["game", "controller", "play"] },
  { symbol: "🎨", keywords: ["paint", "art", "palette"] },
  { symbol: "🎬", keywords: ["movie", "film", "clapperboard"] },
  { symbol: "🎓", keywords: ["graduation", "hat", "education"] },
  { symbol: "💡", keywords: ["idea", "lightbulb", "think"] },
  { symbol: "📚", keywords: ["book", "reading", "study"] },
  { symbol: "✏️", keywords: ["pencil", "write", "draw"] },
  { symbol: "📝", keywords: ["note", "writing", "journal"] },
  { symbol: "📷", keywords: ["camera", "photo", "picture"] },
  { symbol: "🕹️", keywords: ["joystick", "gaming", "arcade"] },
];
// Display all emojis initially
displayEmojis(emojis);

// Add event listener to search input
searchInput.addEventListener("input", filterEmojis);
